import type { ExamOverview } from "./schema";

const CAMBRIDGE_TIMETABLE = "https://www.cambridgeinternational.org/Images/757650-november-2026-zone-5-timetable.pdf";
const PEARSON_TIMETABLE = "https://qualifications.pearson.com/content/dam/pdf/Support/Examination-timetables-for-Edexcel-International-GCSE/intgcse-nov-2026-final.pdf";
const PEARSON_R_TIMETABLE = "https://qualifications.pearson.com/content/dam/pdf/Support/Examination-timetables-for-Edexcel-International-GCSE/int-gcse-r-paper-summer-2027-final.pdf";
const LOCAL = "/exam-materials";

const release = {
  status: "approved" as const,
  approvedAt: "2026-07-15",
  verifiedAt: "2026-07-15",
  schedule: { normal: "每周检查考试时间表", nearExam: "距考试 60 天内每日检查", materials: "每月检查考纲与公式表" },
};

export const EXPANSION_EXAM_OVERVIEWS: ExamOverview[] = [
  {
    id: "cambridge-0606",
    board: "Cambridge International",
    qualification: "Cambridge IGCSE Additional Mathematics",
    code: "0606",
    region: { label: "中国大陆 · Zone 5", note: "默认按上海对应的 Cambridge Administrative Zone 5 展示；考点仍应使用官方区域工具核对。" },
    examSeries: [{ name: "June" }, { name: "November" }, { name: "March", note: "仅印度" }],
    paperCount: "2 张必考试卷；两张各占资格总分的 50%。",
    nextExam: { date: "2026-09-30", session: "AM", code: "0606/13", title: "Paper 1 · Non-calculator", durationMinutes: 120 },
    components: [
      { code: "Paper 1", name: "Non-calculator", durationMinutes: 120, marks: 80, weighting: "50%", calculator: "not-allowed" },
      { code: "Paper 2", name: "Calculator", durationMinutes: 120, marks: 80, weighting: "50%", calculator: "required", note: "需要科学计算器" },
    ],
    routes: [{ id: "all-candidates", level: "IGCSE · grades A*–E", label: "Single route", papers: ["Paper 1", "Paper 2"], note: "两张均为必考。" }],
    calculator: { status: "mixed", summary: "Paper 1 禁止计算器；Paper 2 需要科学计算器。", prohibited: ["图形计算器", "符号代数、微分或积分"] },
    formula: { supplied: true, summary: "每张试卷第 2 页印有公式列表，但列表并不完整；微积分公式不在列表内。" },
    upcomingSeries: "November 2026 · Zone 5",
    timetableStatus: "Final · Version 1 · April 2026",
    upcomingExams: [
      { date: "2026-09-30", session: "AM", code: "0606/13", title: "Paper 1 · Non-calculator", durationMinutes: 120 },
      { date: "2026-10-06", session: "AM", code: "0606/23", title: "Paper 2 · Calculator", durationMinutes: 120 },
    ],
    materials: [
      { id: "0606-timetable", type: "timetable", title: "November 2026 Zone 5 Final Timetable", version: "Version 1 · April 2026", status: "current", officialUrl: CAMBRIDGE_TIMETABLE, previewUrl: `${LOCAL}/november-2026-zone-5-timetable-v1.pdf` },
      { id: "0606-current", type: "syllabus", title: "0606 Syllabus 2025–2027", version: "Version 1", status: "current", officialUrl: "https://www.cambridgeinternational.org/Images/662470-2025-2027-syllabus.pdf", previewUrl: `${LOCAL}/0606-syllabus-2025-2027-v1.pdf` },
      { id: "0606-future", type: "syllabus", title: "0606 Syllabus 2028–2030", version: "Version 1 · September 2025", status: "future", officialUrl: "https://www.cambridgeinternational.org/Images/745683-2028-2030-syllabus.pdf", previewUrl: `${LOCAL}/0606-syllabus-2028-2030-v1.pdf`, note: "官方说明：无影响教学的重大变化。" },
      { id: "0606-formula", type: "formula", title: "试卷内公式列表", version: "Current syllabus · page 22", status: "reference", officialUrl: "https://www.cambridgeinternational.org/Images/662470-2025-2027-syllabus.pdf#page=22", previewUrl: `${LOCAL}/0606-syllabus-2025-2027-v1.pdf#page=22`, note: "公式列表印在考试试卷中，并非独立公式册。" },
    ],
    release,
  },
  {
    id: "cambridge-0607",
    board: "Cambridge International",
    qualification: "Cambridge IGCSE International Mathematics",
    code: "0607",
    region: { label: "中国大陆 · Zone 5", note: "默认按上海对应的 Cambridge Administrative Zone 5 展示；考点仍应使用官方区域工具核对。" },
    examSeries: [{ name: "June" }, { name: "November" }, { name: "March", note: "仅印度" }],
    paperCount: "共 6 种试卷；Core 考 Paper 1 + 3 + 5，Extended 考 Paper 2 + 4 + 6。",
    nextExam: { date: "2026-09-29", session: "PM", code: "0607/12 · 0607/22", title: "Core Paper 1 / Extended Paper 2", durationMinutes: 75 },
    components: [
      { code: "Paper 1", name: "Non-calculator", group: "Core", durationMinutes: 75, marks: 60, weighting: "40%", calculator: "not-allowed" },
      { code: "Paper 3", name: "Calculator", group: "Core", durationMinutes: 75, marks: 60, weighting: "40%", calculator: "required", note: "需要图形显示计算器（GDC）" },
      { code: "Paper 5", name: "Investigation", group: "Core", durationMinutes: 75, marks: 40, weighting: "20%", calculator: "required", note: "需要图形显示计算器（GDC）" },
      { code: "Paper 2", name: "Non-calculator", group: "Extended", durationMinutes: 90, marks: 75, weighting: "40%", calculator: "not-allowed" },
      { code: "Paper 4", name: "Calculator", group: "Extended", durationMinutes: 90, marks: 75, weighting: "40%", calculator: "required", note: "需要图形显示计算器（GDC）" },
      { code: "Paper 6", name: "Investigation and Modelling", group: "Extended", durationMinutes: 90, marks: 50, weighting: "20%", calculator: "required", note: "需要图形显示计算器（GDC）" },
    ],
    routes: [
      { id: "core", level: "Core · grades C–G", label: "Core route", papers: ["Paper 1", "Paper 3", "Paper 5"] },
      { id: "extended", level: "Extended · grades A*–E", label: "Extended route", papers: ["Paper 2", "Paper 4", "Paper 6"] },
    ],
    calculator: { status: "mixed", summary: "Paper 1、2 禁止计算器；其余试卷要求使用图形显示计算器（GDC）。", prohibited: ["符号代数", "外部程序或互联网通信"] },
    formula: { supplied: true, summary: "Paper 1–4 印有公式列表；Paper 5–6 所需公式会在相关题目中给出。" },
    upcomingSeries: "November 2026 · Zone 5",
    timetableStatus: "Final · Version 1 · April 2026",
    upcomingExams: [
      { date: "2026-09-29", session: "PM", code: "0607/12", title: "Paper 1 · Core", durationMinutes: 75, group: "Core" },
      { date: "2026-09-29", session: "PM", code: "0607/22", title: "Paper 2 · Extended", durationMinutes: 90, group: "Extended" },
      { date: "2026-10-08", session: "PM", code: "0607/32", title: "Paper 3 · Core", durationMinutes: 75, group: "Core" },
      { date: "2026-10-08", session: "PM", code: "0607/42", title: "Paper 4 · Extended", durationMinutes: 90, group: "Extended" },
      { date: "2026-10-14", session: "PM", code: "0607/52", title: "Paper 5 · Core", durationMinutes: 75, group: "Core" },
      { date: "2026-10-14", session: "PM", code: "0607/62", title: "Paper 6 · Extended", durationMinutes: 90, group: "Extended" },
    ],
    materials: [
      { id: "0607-timetable", type: "timetable", title: "November 2026 Zone 5 Final Timetable", version: "Version 1 · April 2026", status: "current", officialUrl: CAMBRIDGE_TIMETABLE, previewUrl: `${LOCAL}/november-2026-zone-5-timetable-v1.pdf` },
      { id: "0607-current", type: "syllabus", title: "0607 Syllabus 2025–2027", version: "Version 3 · updated February 2024", status: "current", officialUrl: "https://www.cambridgeinternational.org/Images/662472-2025-2027-syllabus.pdf", previewUrl: `${LOCAL}/0607-syllabus-2025-2027-v3.pdf` },
      { id: "0607-future", type: "syllabus", title: "0607 Syllabus 2028–2030", version: "Version 1 · September 2025", status: "future", officialUrl: "https://www.cambridgeinternational.org/Images/745685-2028-2030-syllabus.pdf", previewUrl: `${LOCAL}/0607-syllabus-2028-2030-v1.pdf`, note: "官方说明：无影响教学的重大变化。" },
      { id: "0607-formula", type: "formula", title: "Core / Extended 公式列表", version: "Current syllabus · pages 59–60", status: "reference", officialUrl: "https://www.cambridgeinternational.org/Images/662472-2025-2027-syllabus.pdf#page=59", previewUrl: `${LOCAL}/0607-syllabus-2025-2027-v3.pdf#page=59`, note: "考试内嵌公式，不是独立公式册。" },
    ],
    release,
  },
  {
    id: "cambridge-9231",
    board: "Cambridge International",
    qualification: "Cambridge International AS & A Level Further Mathematics",
    code: "9231",
    region: { label: "中国大陆 · Zone 5", note: "默认按上海对应的 Cambridge Administrative Zone 5 展示；考点仍应使用官方区域工具核对。" },
    examSeries: [{ name: "June" }, { name: "November" }],
    paperCount: "共 4 张试卷；AS Level 考 2 张，完整 A Level 考 4 张。",
    nextExam: { date: "2026-10-07", session: "PM", code: "9231/12", title: "Further Pure Mathematics 1", durationMinutes: 120, group: "AS" },
    components: [
      { code: "Paper 1", name: "Further Pure Mathematics 1", durationMinutes: 120, marks: 75, weighting: "AS 60% / A Level 30%", calculator: "allowed" },
      { code: "Paper 2", name: "Further Pure Mathematics 2", durationMinutes: 120, marks: 75, weighting: "A Level 30%", calculator: "allowed", note: "仅完整 A Level" },
      { code: "Paper 3", name: "Further Mechanics", durationMinutes: 90, marks: 50, weighting: "AS 40% / A Level 20%", calculator: "allowed" },
      { code: "Paper 4", name: "Further Probability & Statistics", durationMinutes: 90, marks: 50, weighting: "AS 40% / A Level 20%", calculator: "allowed" },
    ],
    routes: [
      { id: "as-mechanics", level: "AS Level", label: "Further Mechanics", papers: ["P1", "P3"], note: "两张在同一考季完成。" },
      { id: "as-statistics", level: "AS Level", label: "Further Probability & Statistics", papers: ["P1", "P4"], note: "两张在同一考季完成。" },
      { id: "al-linear", level: "A Level", label: "Linear full A Level", papers: ["P1", "P2", "P3", "P4"] },
      { id: "al-staged-m", level: "A Level · staged", label: "AS P1+P3 → P2+P4", papers: ["P1", "P3", "P2", "P4"] },
      { id: "al-staged-s", level: "A Level · staged", label: "AS P1+P4 → P2+P3", papers: ["P1", "P4", "P2", "P3"] },
    ],
    calculator: { status: "all", summary: "全部试卷允许使用具备标准科学函数的计算器，并须写出必要过程。", prohibited: ["图形计算器", "计算机", "符号代数、微分或积分"] },
    formula: { supplied: true, summary: "全部试卷提供 MF19 公式与统计表；该册与 9709 共用。" },
    upcomingSeries: "November 2026 · Zone 5",
    timetableStatus: "Final · Version 1 · April 2026",
    upcomingExams: [
      { date: "2026-10-07", session: "PM", code: "9231/12", title: "Further Pure Mathematics 1", durationMinutes: 120, group: "AS" },
      { date: "2026-10-09", session: "PM", code: "9231/32", title: "Further Mechanics", durationMinutes: 90, group: "AS" },
      { date: "2026-10-23", session: "PM", code: "9231/22", title: "Further Pure Mathematics 2", durationMinutes: 120, group: "AL" },
      { date: "2026-10-30", session: "PM", code: "9231/42", title: "Further Probability & Statistics", durationMinutes: 90, group: "AS" },
    ],
    materials: [
      { id: "9231-timetable", type: "timetable", title: "November 2026 Zone 5 Final Timetable", version: "Version 1 · April 2026", status: "current", officialUrl: CAMBRIDGE_TIMETABLE, previewUrl: `${LOCAL}/november-2026-zone-5-timetable-v1.pdf` },
      { id: "9231-current", type: "syllabus", title: "9231 Syllabus 2026–2027", version: "Version 3", status: "current", officialUrl: "https://www.cambridgeinternational.org/Images/697357-2026-2027-syllabus.pdf", previewUrl: `${LOCAL}/9231-syllabus-2026-2027-v3.pdf`, note: "两个官方文件对 Version 3 发布月份表述不同，因此前台只显示版本号。" },
      { id: "9231-future", type: "syllabus", title: "9231 Syllabus 2028–2030", version: "Version 1 · September 2025", status: "future", officialUrl: "https://www.cambridgeinternational.org/Images/744603-2028-2030-syllabus.pdf", previewUrl: `${LOCAL}/9231-syllabus-2028-2030-v1.pdf`, note: "官方说明：无影响教学的重大变化。" },
      { id: "9231-mf19", type: "formula", title: "MF19 公式与统计表", version: "2025 official booklet", status: "reference", officialUrl: "https://www.cambridgeinternational.org/Images/737429-list-of-formulae-and-statistical-tables-2025.pdf", previewUrl: `${LOCAL}/cambridge-mf19-2025.pdf` },
    ],
    release,
  },
  {
    id: "pearson-4pm1",
    board: "Pearson Edexcel",
    qualification: "International GCSE Further Pure Mathematics (9–1)",
    code: "4PM1",
    region: { label: "中国大陆", note: "November 使用标准试卷；Summer 中国大陆必须使用 R variant。仅展示官方 Morning / Afternoon，不推算当地钟点。" },
    examSeries: [{ name: "November", note: "无 R variant" }, { name: "Summer (May/June)", note: "中国大陆使用 R variant" }],
    paperCount: "2 张 Higher tier 试卷；两张必须在同一考季完成。",
    nextExam: { date: "2026-10-30", session: "Morning", code: "4PM1 01", title: "Paper 1", durationMinutes: 120, group: "Higher" },
    components: [
      { code: "4PM1/01", name: "Paper 1", group: "Higher", durationMinutes: 120, marks: 100, weighting: "50%", calculator: "required" },
      { code: "4PM1/02", name: "Paper 2", group: "Higher", durationMinutes: 120, marks: 100, weighting: "50%", calculator: "required" },
    ],
    routes: [{ id: "higher", level: "Higher · grades 9–4（允许 3）", label: "Linear route", papers: ["Paper 1", "Paper 2"], note: "两张必须在同一考季完成；重考也须重考两张。" }],
    calculator: { status: "all", summary: "两张试卷均要求合适的电子计算器。", prohibited: ["资料库或文字/公式检索", "QWERTY 键盘", "符号代数、微分或积分"] },
    formula: { supplied: true, summary: "每张书面考试均包含 Appendix 4 公式表；另有部分公式要求考生记忆。" },
    upcomingSeries: "November 2026",
    timetableStatus: "Final",
    upcomingExams: [
      { date: "2026-10-30", session: "Morning", code: "4PM1 01", title: "Paper 1", durationMinutes: 120, group: "Higher" },
      { date: "2026-11-10", session: "Morning", code: "4PM1 02", title: "Paper 2", durationMinutes: 120, group: "Higher" },
    ],
    materials: [
      { id: "4pm1-timetable", type: "timetable", title: "International GCSE November 2026 Timetable", version: "Final", status: "current", officialUrl: PEARSON_TIMETABLE, previewUrl: `${LOCAL}/pearson-intgcse-november-2026-final.pdf` },
      { id: "4pm1-r-timetable", type: "timetable", title: "International GCSE Summer 2027 R Timetable", version: "Final · China R papers", status: "future", officialUrl: PEARSON_R_TIMETABLE, previewUrl: `${LOCAL}/pearson-intgcse-r-paper-summer-2027-final.pdf` },
      { id: "4pm1-spec", type: "syllabus", title: "International GCSE Further Pure Mathematics Specification", version: "Issue 1", status: "current", officialUrl: "https://qualifications.pearson.com/content/dam/pdf/International%20GCSE/Further%20Pure%20Mathematics/2016/Specification%20and%20sample%20assessments/international-gcse-in-further-pure-mathematics-spec.pdf", previewUrl: `${LOCAL}/4pm1-specification-issue1.pdf` },
      { id: "4pm1-formula", type: "formula", title: "Appendix 4 · Formulae sheet for examinations", version: "Specification page 37", status: "reference", officialUrl: "https://qualifications.pearson.com/content/dam/pdf/International%20GCSE/Further%20Pure%20Mathematics/2016/Specification%20and%20sample%20assessments/international-gcse-in-further-pure-mathematics-spec.pdf#page=43", previewUrl: `${LOCAL}/4pm1-specification-issue1.pdf#page=43` },
    ],
    release,
  },
  {
    id: "pearson-4mb1",
    board: "Pearson Edexcel",
    qualification: "International GCSE Mathematics B (9–1)",
    code: "4MB1",
    region: { label: "中国大陆", note: "November 使用标准试卷；Summer 中国大陆必须使用 R variant。仅展示官方 Morning / Afternoon，不推算当地钟点。" },
    examSeries: [{ name: "November", note: "无 R variant" }, { name: "Summer (May/June)", note: "中国大陆使用 R variant" }],
    paperCount: "2 张 Higher tier 试卷；两张必须在同一考季完成。",
    nextExam: { date: "2026-10-29", session: "Morning", code: "4MB1 01", title: "Paper 1", durationMinutes: 90, group: "Higher" },
    components: [
      { code: "4MB1/01", name: "Paper 1", group: "Higher", durationMinutes: 90, marks: 100, weighting: "33⅓%", calculator: "required" },
      { code: "4MB1/02", name: "Paper 2", group: "Higher", durationMinutes: 150, marks: 100, weighting: "66⅔%", calculator: "required" },
    ],
    routes: [{ id: "higher", level: "Higher · grades 9–4（允许 3）", label: "Linear route", papers: ["Paper 1", "Paper 2"], note: "两张必须在同一考季完成；重考也须重考两张。" }],
    calculator: { status: "all", summary: "两张试卷均要求合适的电子计算器。", prohibited: ["资料库或文字/公式检索", "QWERTY 键盘", "符号代数、微分或积分"] },
    formula: { supplied: false, summary: "不提供独立公式表；Paper 2 若需要 Appendix 4 中的公式，会在相关题目末尾直接给出。" },
    upcomingSeries: "November 2026",
    timetableStatus: "Final",
    upcomingExams: [
      { date: "2026-10-29", session: "Morning", code: "4MB1 01", title: "Paper 1", durationMinutes: 90, group: "Higher" },
      { date: "2026-11-09", session: "Morning", code: "4MB1 02", title: "Paper 2", durationMinutes: 150, group: "Higher" },
    ],
    materials: [
      { id: "4mb1-timetable", type: "timetable", title: "International GCSE November 2026 Timetable", version: "Final", status: "current", officialUrl: PEARSON_TIMETABLE, previewUrl: `${LOCAL}/pearson-intgcse-november-2026-final.pdf` },
      { id: "4mb1-r-timetable", type: "timetable", title: "International GCSE Summer 2027 R Timetable", version: "Final · China R papers", status: "future", officialUrl: PEARSON_R_TIMETABLE, previewUrl: `${LOCAL}/pearson-intgcse-r-paper-summer-2027-final.pdf` },
      { id: "4mb1-spec", type: "syllabus", title: "International GCSE Mathematics B Specification", version: "Issue 1", status: "current", officialUrl: "https://qualifications.pearson.com/content/dam/pdf/International%20GCSE/Mathematics%20B/2016/Specification%20and%20sample%20assessments/international-gcse-in-mathematics-spec-b.pdf", previewUrl: `${LOCAL}/4mb1-specification-issue1.pdf` },
      { id: "4mb1-formula", type: "formula", title: "Appendix 4 · Formulae reference", version: "Specification page 39", status: "reference", officialUrl: "https://qualifications.pearson.com/content/dam/pdf/International%20GCSE/Mathematics%20B/2016/Specification%20and%20sample%20assessments/international-gcse-in-mathematics-spec-b.pdf#page=45", previewUrl: `${LOCAL}/4mb1-specification-issue1.pdf#page=45`, note: "仅作为官方参考预览；考试不提供独立公式表。" },
    ],
    release,
  },
];
