packages:
  - .

overrides:
  postcss: 8.5.16
  undici: 7.28.0
  ws: 8.21.0

allowBuilds:
  core-js: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true

onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
